DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS siteViews;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email TEXT,
	username TEXT NOT NULL CHECK( length(username) <= 32),
	password TEXT NOT NULL
);

CREATE TABLE siteViews (
	views INTEGER DEFAULT 0
);


